site_name: Dexaminds Engineering Handbook
theme:
  name: material
nav:
  - Home: index.md
  - Team Culture:
      - Code of Conduct: handbook/team-culture/code-of-conduct.md
      - Communication: handbook/team-culture/communication.md
  - Coding Standards:
      - Python: handbook/coding-standards/python.md
      - JavaScript: handbook/coding-standards/javascript.md
  - Development Practices:
      - Git Workflow: handbook/development-practices/git-workflow.md
      - Testing Strategy: handbook/development-practices/testing-strategy.md
  - Career Growth:
      - Leveling Framework: handbook/career-growth/leveling-framework.md
      - Mentorship: handbook/career-growth/mentorship.md
