site_name: Engineering Handbook
site_url: https://dexaminds.github.io/engineering-handbook/
theme:
  name: material

nav:
  - Home: index.md
  - Coding Standards:
      - JavaScript: coding-standards/javascript.md
      - Python: coding-standards/python.md
  - Development Practices:
      - Git Workflow: development-practices/git-workflow.md
      - Testing Strategy: development-practices/testing-strategy.md
  - Team Culture:
      - Communication: team-culture/communication.md
      - Code of Conduct: team-culture/code-of-conduct.md
  - Career Growth:
      - Leveling Framework: career-growth/leveling-framework.md
      - Mentorship: career-growth/mentorship.md
