name: Sync Submodules and Deploy (Sparse Checkout)

on:
  schedule:
    - cron: '59 11 * * *'
  workflow_dispatch:

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          ssh-key: ${{ secrets.GH_SSH_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup sparse checkouts
        run: |
          chmod +x ./scripts/setup-sparse-checkout.sh
          ./scripts/setup-sparse-checkout.sh

      - name: Commit documentation changes
        run: |
          chmod +x ./scripts/commit-doc-changes.sh
          ./scripts/commit-doc-changes.sh "chore: update documentation submodules"

      - name: Install MkDocs dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-macros-plugin

      - name: Deploy updated docs site
        run: mkdocs gh-deploy --force
