name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          ssh-key: ${{ secrets.GH_SSH_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update submodules to latest commits
        run: git submodule update --init --recursive --remote

      - name: Apply sparse checkout filters
        run: |
          # API Guidelines
          if [ -d "docs/api-guidelines" ]; then
            cd docs/api-guidelines
            git sparse-checkout init --cone
            git sparse-checkout set --skip-checks README.md \
              design-principles.md \
              rest-guidelines.md \
              graphql-guidelines.md \
              versioning.md \
              error-handling.md \
              security.md
            cd ../../..
          fi

          # Engineering Handbook
          if [ -d "docs/engineering-handbook" ]; then
            cd docs/engineering-handbook
            git sparse-checkout init --cone
            git sparse-checkout set --skip-checks README.md \
              coding-standards \
              development-practices
            cd ../../..
          fi

          # Internal Docs
          if [ -d "docs/internal-docs" ]; then
            cd docs/internal-docs
            git sparse-checkout init --cone
            git sparse-checkout set --skip-checks README.md \
              processes \
              tutorials
            cd ../../..
          fi

      - name: Install MkDocs and plugins
        run: |
          pip install mkdocs mkdocs-material mkdocs-macros-plugin

      - name: Build and deploy to GitHub Pages
        run: mkdocs gh-deploy --force
